spring:
  application:
    name: cornichon
webdriver:
  browser: ${WEBDRIVER_BROWSER:chrome}
  downloadFolder: ${WEBDRIVER_DOWNLOAD_FOLDER:download}
  headless: ${WEBDRIVER_HEADLESS:false}
  remote: ${WEBDRIVER_REMOTE:false}
  server:
    host: ${WEBDRIVER_HOST:127.0.0.1}
    port: ${WEBDRIVER_PORT:4444}
durations:
  baseline: 10
  writing: 5
  reading: 5
  visibility: 5
  clicking: 5
